### ISSUE TITLE
Finish quiz

### ISSUE THREAD

**Issue by Bruno12leonel** [quickbirdstudios/survey_kit#12]
Hi, I have a question regarding when the questionnaire is finished.
I'm using the example from the page. However, when the questionnaire ends, the application goes to a completely black screen.
I would like to know how do I go to a custom screen.
What I want is to present a simple screen saying that the questionnaire has already been answered.

**Comment by Numoy** [comment]
Hi,

the idea is that you open the 'SurveyKit' Widget via Navigation, e.g. by calling

```dart
Navigator.push(
    context,
    MaterialPageRoute(builder: (context) => SurveyKit()),
  );
```
After the Survey Navigator.pop(context) is called and you will go back to the Widget where you called Navigator.push.
Another way to control what happens after the Survey is finished  is to override the `onCloseSurvey` Method in the SurveyController.

**Comment by alpapado** [comment]
Is it possible that the onCloseSurvey is called only when the questionnaire is aborted? Finishing the questionnaire seems to NOT call the onCloseSurvey Method. Is it possible to somehow handle navigation behavior after completing the questionnaire?

**Comment by Numoy** [comment]
Hi sorry for the late response.

It is true onCloseSurvey is only called when the survey is aborted. One way to change the behaviour/navigation, when the survey is finished, is to override the  'onResult' Function in SurveyKit. There you can listen when and why the survey was finished (finished,discarded,...) and do the navigation.

**Comment by waletoyo1** [comment]
> Hi sorry for the late response.
> 
> It is true onCloseSurvey is only called when the survey is aborted. One way to change the behaviour/navigation, when the survey is finished, is to override the 'onResult' Function in SurveyKit. There you can listen when and why the survey was finished (finished,discarded,...) and do the navigation.

Hi, thanks for the contribution. How can the onResult callback be overridden?

**Comment by Numoy** [comment]
You can just override this in the 'SurveyKit' widget:

```dart
SurveyKit(
                    onResult: (SurveyResult result) {
                      print(result.finishReason);
                    },
....
```
