### ISSUE TITLE
For `SingleChoiceAnswerFormat`,  `isOptional` flag not working

### ISSUE THREAD

**Issue by sohail0992** [quickbirdstudios/survey_kit#22]
```
    this.questions.asMap().forEach((index, each) => {
          choices = [],
          each['options'].forEach((eachOption) {
            choices.add(TextChoice(
                text: capitalize(eachOption['text']),
                value: eachOption['text']));
          }),
          steps.add(QuestionStep(
              isOptional: false,
              id: StepIdentifier(id: index.toString()),
              title: 'Question ' + index.toString() + '/' + total.toString(),
              text: each['question'],
              answerFormat: SingleChoiceAnswerFormat(
                  defaultSelection: null, textChoices: choices)))
        });
```
Even if I mark the `isOptional` false, I am able to skip the question by clicking next button, my Goal is to restrict the user.

**Comment by sohail0992** [comment]
@Numoy is this fix in process?

**Comment by Numoy** [comment]
Sorry for the delay. I will provide a fix this week.

**Comment by Numoy** [comment]
Fixed in version 0.0.12

**Comment by sohail0992** [comment]
@Numoy  Updated the package to version 0.0.12, still on pressing next without any selection, next question appear. Below is snippet of how I am constructing the QuestionStep.

```
QuestionStep(
      stepIdentifier: StepIdentifier(id: index.toString()),
      title: 'Question ' + index.toString() + '/' + total.toString(),
      text: each['question'],
      answerFormat: SingleChoiceAnswerFormat(
          textChoices: choices
      )
 )}
```

**Comment by Numoy** [comment]
Found the issue: The check in the validation function for the "isOptional" was missing. I fixed that and merged it into the develop branch. 

It will be released at the end of the week with some other new features.

**Comment by sohail0992** [comment]
@Numoy any update?

**Comment by sohail0992** [comment]
Also I tested the dev branch this issue is fixed but on submitting the survey `onResult` method doesn't trigger.
