### ISSUE TITLE
Getting error when running `flutter build apk` on project in which survey_kit is imported

### ISSUE THREAD

**Issue by sohail0992** [quickbirdstudios/survey_kit#26]
```
/opt/hostedtoolcache/flutter/2.4.0-4.2.pre-beta/x64/.pub-cache/hosted/pub.dartlang.org/survey_kit-0.0.11/lib/src/views/time_answer_view.dart:82:14: Error: 'TimePickerDialog' is imported from both 'package:flutter/src/material/time_picker.dart' and 'package:survey_kit/src/views/widget/time_picker.dart'.
      child: TimePickerDialog(
```

**Comment by nayi10** [comment]
> ```
> /opt/hostedtoolcache/flutter/2.4.0-4.2.pre-beta/x64/.pub-cache/hosted/pub.dartlang.org/survey_kit-0.0.11/lib/src/views/time_answer_view.dart:82:14: Error: 'TimePickerDialog' is imported from both 'package:flutter/src/material/time_picker.dart' and 'package:survey_kit/src/views/widget/time_picker.dart'.
>       child: TimePickerDialog(
> ```

Also facing same issue

**Comment by Numoy** [comment]
It looks like the problem only occurs if your are not on the Stable-Channel, because the API for the TimerPicker changed. I will provider a fix later this week.

**Comment by nayi10** [comment]
> It looks like the problem only occurs if your are not on the Stable-Channel, because the API for the TimerPicker changed. I will provider a fix later this week.

That could be the issue. For my case, I chose to hide the `TimePickerDialog` from *material* library to solve the problem.

**Comment by sohail0992** [comment]
using stable channel fix the issue for me.
