### ISSUE TITLE
[bug] huge issue about QuestionResult.valueIdentifier 

### ISSUE THREAD

**Issue by mohammedali933** [quickbirdstudios/survey_kit#34]
as defined in the plugin answer creation process:
TextChoice(text: answer.text, value: answer.id);
i think the TextChoice value may vary from the TextChoice text
So i think the QuestionResult.valueIdentifier should equal to TextChoice.value not as it is now Textchoice.text

**Comment by Numoy** [comment]
Yes fpr the value identifier the result should be used.
-> Will be planned in for the next release.
