### ISSUE TITLE
Get sum of value answers

### ISSUE THREAD

**Issue by carlobaratto** [quickbirdstudios/survey_kit#42]
Hi all,
on my QuestionStep:
        QuestionStep(
          title: 'Congestive heart failure within the past month',
          answerFormat: const SingleChoiceAnswerFormat(
            textChoices: [
              TextChoice(text: 'Yes', value: '1'),
              TextChoice(text: 'No', value: '0'),
            ],
            defaultSelection: TextChoice(text: 'No', value: '0'),
          ),
        ),
I see the text and value for each answer, I'm not able to see the value of all the answers when I finish the survey, only the text. 
My need is to sum all the value... there is a way to do it?

**Comment by Numoy** [comment]
Hey, sorry for the late response.

Here is an example of one of my projects where i calculate a score from the answers:
```dart
var score = 0;
    for (var stepResult in result.results) {
      for (var questionResult in stepResult.results) {
        if (questionResult is SingleChoiceQuestionResult) {
          score += int.parse(questionResult.result?.value as String);
        }
      }
    }
    return score;
```
