### ISSUE TITLE
Because survey_kit >=0.0.10 depends on provider ^5.0.0 and agenda depends on provider ^6.0.1, survey_kit >=0.0.10 is forbidden.

### ISSUE THREAD

**Issue by juancho108** [quickbirdstudios/survey_kit#43]
Hi, I have an error with this package. When I try to install it, it tells me that survey_kit> = 0.0.10 depends on provider ^ 5.0.0 and that my app depends on provider ^ 6.0.1. How can i fix this?

**Comment by Numoy** [comment]
This will be fixed with next update where we update all dependencies.
As a workaround you can add this to your pubspec.yaml in your project:

```yml
dependency_overrides:
  provider: ^6.0.0
```

**Comment by juancho108** [comment]
First, thank you for your quick response.
Unfortunately I will have to wait for the update, because the only way it works is using provider ^ 5.0.0 but I have other packages that depend on provider ^ 6.0.1.
If I put provider 6.0.0, as you have suggested, it doesn't work, since survey_kit currently needs 5.0.0.
I thank you once again for your response and I await the update to be able to use it.
