### ISSUE TITLE
Got problem when add the dependecy.

### ISSUE THREAD

**Issue by aeg6430** [quickbirdstudios/survey_kit#57]
I followed the steps and I got some problems,how to solve it?

![1](https://user-images.githubusercontent.com/80158406/156771939-4eb96ce6-54ae-4d99-87f8-6661e2c05f41.png)
![2](https://user-images.githubusercontent.com/80158406/156771932-7673f932-dd1a-4b3c-9c7b-8c7cb63fe2b0.png)

**Comment by syncdoth** [comment]
I found that it was actually `survey_kit`...

**Comment by aeg6430** [comment]
> I found that it was actually `survey_kit`...
![未命名](https://user-images.githubusercontent.com/80158406/156929811-df305476-f42e-4cb1-b979-eb9ec0a3c328.png)
It still not working,is it possible to import all the  file in the zip  into the project?
