### ISSUE TITLE
Issues with bloc dependencies

### ISSUE THREAD

**Issue by BJRichardsAZ** [quickbirdstudios/survey_kit#58]
When trying to implement this package with our project we have a conflict in dependencies; namely we are relying on a bloc version in which mapEventToState has been deprecated (bloc 8.0.0 or greater). In the future will the bloc dependency of the package be updated to usable with projects depending on newer versions of bloc?

**Comment by ignertic** [comment]
> When trying to implement this package with our project we have a conflict in dependencies; namely we are relying on a bloc version in which mapEventToState has been deprecated (bloc 8.0.0 or greater). In the future will the bloc dependency of the package be updated to usable with projects depending on newer versions of bloc?

I ran into this problem as well but don't you worry mate, I have opened a Pull Request #59 that addresses the issue. I'm sure the authors can looking into it but in the meantime if you're in a hurry , just switch to the PR branch here temporarily till the PR gets merged.

Happy Coding!!

**Comment by Numoy** [comment]
Thanks, @ignertic for the fix. I merged the PR and will release the version soon to pub.dev - When released I will close this issue.
