### ISSUE TITLE
Unable to load in getJsonTask() from example code

### ISSUE THREAD

**Issue by gerryau** [quickbirdstudios/survey_kit#68]
When I try to run the following `getJsonTask()` from the example code, the app just stays on the loading screen for some time.
Using Flutter 3.0.1

```dart
class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          color: Colors.white,
          child: Align(
            alignment: Alignment.center,
            child: FutureBuilder<Task>(
              future: getJsonTask(), //HERE
              builder: (context, snapshot) {
                     .....
```

Running `getSampleTask()` it works fine.

**Comment by gerryau** [comment]
Bump.

**Comment by Numoy** [comment]
Hi gerryau,

thanks for letting me know! I fixed the issue and it should work again.

Best
Marvin

**Comment by binaryjc** [comment]
[latest update](https://github.com/QuickBirdEng/survey_kit/commit/767c5e4c5c9daad6f9c4865237a7a4d1d674e6ed) on example json might have broke it. I cant load it using getJsonTask() on sample app. I tried using the old format on [pub.dev](https://pub.dev/packages/survey_kit#start-the-survey), it works fine.

**Comment by Technorocker** [comment]
Im just trying the example right now and getting same issue, loading onto chrome debugging from vscode leaves it at progression spinner, the getsampletask still works though. Does the json approach work? I think that would be better to create a questionnaie file for a large dataset or questions and answers.

**Comment by Numoy** [comment]
I will look into it. Thanks for letting me know.
