### ISSUE TITLE
Using SurveyKit in a Future for API database loading

### ISSUE THREAD

**Issue by agus-tin** [quickbirdstudios/survey_kit#7]
Hi,
I'd like to congratulate you on this excellent work you did here.
I just have a question that I'm sure is due to my lack of expertise with Flutter/Dart, than with your work.
I'm trying to load the questions from a database through a NodeJS API & Mongo DB as backend, everything seem to work just fine, but when I call SurveyKit from a Future Builder (see code below), as soon as I tap/click on the Answer text field it takes me immediately the InstructionsStep screen.
Can you please guide me on what am I missing here?
...
FutureBuilder(
          future: getQuestionSteps(surveyId:'1'),
          builder: (ctx, snapshot) {
            // Checking if future is resolved or not
            if (snapshot.connectionState == ConnectionState.done) {
              // If we got an error
              if (snapshot.hasError) {
                return Center(
                  child: Text(
                    '${snapshot.error} occured',
                    style: TextStyle(fontSize: 18),
                  ),
                );
                // if we got our data
              } else if (snapshot.hasData) {
                // Extracting data from snapshot object
                final questionSteps = snapshot.data;
                return **Survey.SurveyKit(
                            onResult: (Survey.SurveyResult result) {
                              print(result.finishReason);
                            },
                            task: getSampleTask()
                )**;
              }
            }
            // Displaying LoadingSpinner to indicate waiting state
            return Center(
              child: CircularProgressIndicator(),
            );
          },
        )
```

**Comment by Numoy** [comment]
Hi, first of all  thanks for your feedback.

I tried a similar example by wrapping the "getTask" method in the example with a future and used that in the FutureBuilder. It works completly fine for me. 

Maybe your build method with the FutureBuilder is called several times, so your backend is called more than once, which could result in a rebuild of the survey.
Hope that helps you.

**Comment by Numoy** [comment]
So i tried it again with your code sample. I modified it a little bit but it should be quite similar to your example:

```dart
import 'package:flutter/material.dart';
import 'package:survey_kit/survey_kit.dart' as Survey;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SurveyForm(),
      ),
    );
  }
}

class SurveyForm extends StatefulWidget {
  @override
  _SurveyFormState createState() => _SurveyFormState();
}

class _SurveyFormState extends State<SurveyForm> {
  Future<List<Survey.Step>> getQuestionSteps() async {
    List<Survey.Step> questionSteps = List.filled(
        1,
        Survey.InstructionStep(
          title: 'Your journey starts here',
          text:
              'In order to identify actions and possibilities for the coaching process, the coachee is asked to answer the following questions. This is an open exploration, the coach presents himself totally available and at the service of the coachee, to find out their current energy for change, in intensity and direction.	',
          buttonText: 'START QUESTIONNAIRE',
        ),
        growable: true);
    final _questions = [
      Survey.QuestionStep(
        title: 'How old are you?',
        answerFormat: Survey.IntegerAnswerFormat(
          defaultValue: 25,
          hint: 'Please enter your age',
        ),
      ),
      Survey.QuestionStep(
        title: 'Medication?',
        text: 'Are you using any medication',
        answerFormat: Survey.BooleanAnswerFormat(
          positiveAnswer: 'Yes',
          negativeAnswer: 'No',
          result: Survey.BooleanResult.POSITIVE,
        ),
      ),
      Survey.QuestionStep(
        title: 'Tell us about you',
        text: 'Tell us about yourself and why you want to improve your health.',
        answerFormat: Survey.TextAnswerFormat(
          maxLines: 5,
        ),
      ),
      Survey.QuestionStep(
        title: 'Select your body type',
        answerFormat: Survey.ScaleAnswerFormat(
          step: 1,
          minimumValue: 1,
          maximumValue: 5,
          defaultValue: 3,
          minimumValueDescription: '1',
          maximumValueDescription: '5',
        ),
      ),
    ];
    questionSteps.addAll(_questions);
    questionSteps.add(Survey.CompletionStep(
      id: Survey.StepIdentifier(id: '1123123'),
      title: 'You are done',
      text: 'You have finished !!!',
      buttonText: 'Submit survey',
    ));
    return questionSteps;
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    return MaterialApp(
      home: Scaffold(
          body: FutureBuilder<List<Survey.Step>>(
        future: getQuestionSteps(),
        builder: (ctx, snapshot) {
          // Checking if future is resolved or not
          if (snapshot.connectionState == ConnectionState.done) {
            // If we got an error
            if (snapshot.hasError) {
              return Center(
                child: Text(
                  '${snapshot.error} occured',
                  style: TextStyle(fontSize: 18),
                ),
              );
              // if we got our data
            } else if (snapshot.hasData) {
              // Extracting data from snapshot object
              final questionSteps = snapshot.data!;
              return Survey.SurveyKit(
                  onResult: (Survey.SurveyResult result) {
                    print(result.finishReason);
                  },
                  task: getSampleTask(questionSteps));
            }
          }
          // Displaying LoadingSpinner to indicate waiting state
          return Center(
            child: CircularProgressIndicator(),
          );
        },
      )),
    );
  }

  Survey.Task getSampleTask(List<Survey.Step> _questionSteps) {
    var task = Survey.NavigableTask(
      id: Survey.TaskIdentifier(),
      steps: _questionSteps,
    );
    task.addNavigationRule(
      forTriggerStepIdentifier: task.steps[2].id,
      navigationRule: Survey.ConditionalNavigationRule(
        resultToStepIdentifierMapper: (input) {
          switch (input) {
            case "Yes":
              return task.steps[0].id;
            case "No":
              return task.steps[3].id;
            default:
              return null;
          }
        },
      ),
    );
    return task;
  }
}
```

It still does work for me. One thing i noticed is that you have some navigation rules in place. If on the third step the user types/clicks "Yes" (The valueIdentifier) the user goes back to the first Step (InstructionsStep). Maybe that is the reason?

```dart
 task.addNavigationRule(
      forTriggerStepIdentifier: task.steps[2].id,
      navigationRule: Survey.ConditionalNavigationRule(
        resultToStepIdentifierMapper: (input) {
          switch (input) {
            case "Yes":
              return task.steps[0].id;
            case "No":
              return task.steps[3].id;
            default:
              return null;
          }
        },
      ),
    );
```

**Comment by agus-tin** [comment]
Hi Marvin, thanks so much for replying.
You’re right, your code is working in a brand new project. If I enable the loading of the questions from the database in such a brand-new project using this code, it still works fine.
Something that might be improved is that when there are consecutive “Text Entry” questions, the text of Second question keeps the text entered in the first one, so if I want to answer Question 2 (and so on), I need to manually remove previous answer’s text.

In my actual project, using the code you’re sharing below, as soon as I tap on the entry text field, it takes me back to the start of the survey (even if I remove the navigation, it behaves the same).
I guess there is some configuration in my project that create this behavior (versus a brand-new project, where if works fine)

Again, thanks for taking the time to reply. I’ll keep researching, I let you know if I can get it to work.
Kind regards



From: Marvin März ***@***.***>
Sent: Friday, May 14, 2021 6:54 AM
To: quickbirdstudios/survey_kit ***@***.***>
Cc: Agustin Garcia Romero ***@***.***>; Author ***@***.***>
Subject: [SPAM] Re: [quickbirdstudios/survey_kit] Using SurveyKit in a Future for API database loading (#7)
Importance: Low

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


So i tried it again with your code sample. I modified it a little bit but it should be quite similar to your example:

import 'package:flutter/material.dart';

import 'package:survey_kit/survey_kit.dart' as Survey;



void main() {

  runApp(MyApp());

}



class MyApp extends StatefulWidget {

  @override

  _MyAppState createState() => _MyAppState();

}



class _MyAppState extends State<MyApp> {

  @override

  Widget build(BuildContext context) {

    return MaterialApp(

      home: Scaffold(

        body: SurveyForm(),

      ),

    );

  }

}



class SurveyForm extends StatefulWidget {

  @override

  _SurveyFormState createState() => _SurveyFormState();

}



class _SurveyFormState extends State<SurveyForm> {

  Future<List<Survey.Step>> getQuestionSteps() async {

    List<Survey.Step> questionSteps = List.filled(

        1,

        Survey.InstructionStep(

          title: 'Your journey starts here',

          text:

              'In order to identify actions and possibilities for the coaching process, the coachee is asked to answer the following questions. This is an open exploration, the coach presents himself totally available and at the service of the coachee, to find out their current energy for change, in intensity and direction. ',

          buttonText: 'START QUESTIONNAIRE',

        ),

        growable: true);

    final _questions = [

      Survey.QuestionStep(

        title: 'How old are you?',

        answerFormat: Survey.IntegerAnswerFormat(

          defaultValue: 25,

          hint: 'Please enter your age',

        ),

      ),

      Survey.QuestionStep(

        title: 'Medication?',

        text: 'Are you using any medication',

        answerFormat: Survey.BooleanAnswerFormat(

          positiveAnswer: 'Yes',

          negativeAnswer: 'No',

          result: Survey.BooleanResult.POSITIVE,

        ),

      ),

      Survey.QuestionStep(

        title: 'Tell us about you',

        text: 'Tell us about yourself and why you want to improve your health.',

        answerFormat: Survey.TextAnswerFormat(

          maxLines: 5,

        ),

      ),

      Survey.QuestionStep(

        title: 'Select your body type',

        answerFormat: Survey.ScaleAnswerFormat(

          step: 1,

          minimumValue: 1,

          maximumValue: 5,

          defaultValue: 3,

          minimumValueDescription: '1',

          maximumValueDescription: '5',

        ),

      ),

    ];

    questionSteps.addAll(_questions);

    questionSteps.add(Survey.CompletionStep(

      id: Survey.StepIdentifier(id: '1123123'),

      title: 'You are done',

      text: 'You have finished !!!',

      buttonText: 'Submit survey',

    ));

    return questionSteps;

  }



  @override

  Widget build(BuildContext context) {

    final screenSize = MediaQuery.of(context).size;

    return MaterialApp(

      home: Scaffold(

          body: FutureBuilder<List<Survey.Step>>(

        future: getQuestionSteps(),

        builder: (ctx, snapshot) {

          // Checking if future is resolved or not

          if (snapshot.connectionState == ConnectionState.done) {

            // If we got an error

            if (snapshot.hasError) {

              return Center(

                child: Text(

                  '${snapshot.error} occured',

                  style: TextStyle(fontSize: 18),

                ),

              );

              // if we got our data

            } else if (snapshot.hasData) {

              // Extracting data from snapshot object

              final questionSteps = snapshot.data!;

              return Survey.SurveyKit(

                  onResult: (Survey.SurveyResult result) {

                    print(result.finishReason);

                  },

                  task: getSampleTask(questionSteps));

            }

          }

          // Displaying LoadingSpinner to indicate waiting state

          return Center(

            child: CircularProgressIndicator(),

          );

        },

      )),

    );

  }



  Survey.Task getSampleTask(List<Survey.Step> _questionSteps) {

    var task = Survey.NavigableTask(

      id: Survey.TaskIdentifier(),

      steps: _questionSteps,

    );

    task.addNavigationRule(

      forTriggerStepIdentifier: task.steps[2].id,

      navigationRule: Survey.ConditionalNavigationRule(

        resultToStepIdentifierMapper: (input) {

          switch (input) {

            case "Yes":

              return task.steps[0].id;

            case "No":

              return task.steps[3].id;

            default:

              return null;

          }

        },

      ),

    );

    return task;

  }

}

It still does work for me. One thing i noticed is that you have some navigation rules in place. If on the third step the user types/clicks "Yes" (The valueIdentifier) the user goes back to the first Step (InstructionsStep). Maybe that is the reason?

 task.addNavigationRule(

      forTriggerStepIdentifier: task.steps[2].id,

      navigationRule: Survey.ConditionalNavigationRule(

        resultToStepIdentifierMapper: (input) {

          switch (input) {

            case "Yes":

              return task.steps[0].id;

            case "No":

              return task.steps[3].id;

            default:

              return null;

          }

        },

      ),

    );
