### ISSUE TITLE
Cancel Button Behaviours

### ISSUE THREAD

**Issue by satyajitghana** [quickbirdstudios/survey_kit#8]
Is there an option to override the cancel option behaviour ? or do i have to modify the library

The entire page gets popped if i tap on cancel, I want it to behave like the back button of a scaffold.

**Comment by satyajitghana** [comment]
Thanks ! :)

**Comment by Panz99** [comment]
Is there any news about the override of the cancel option?

**Comment by Numoy** [comment]
The behaviour can now be overriden in version 0.0.10.

```dart
 SurveyKit(
      surveyController: SurveyController(
               onCloseSurvey: (context, resultFunction) => print('Closed'),
       ),
); 
```

If you have any question feel free to open another issue :)
